version: '2'
services:
  grafana:
    image: grafana/grafana
    ports:
    - 3000:3000/tcp
  prometheus:
    image: prom/prometheus:latest
    stdin_open: true
    tty: true
    ports:
    - 9090:9090/tcp
